"""Build the fully static research page. Python standard library only."""
from pathlib import Path
from html import escape

ROOT = Path(__file__).resolve().parents[1]


def film(name, label, *, autoplay=False, speed='', portrait=False, loop=True):
    return f'''<div class="media-frame{' portrait-video' if portrait else ''}">
      <video class="managed-video" {'id="hero-video" data-autoplay' if autoplay else ''} muted playsinline controls {'loop' if loop else ''} preload="none" poster="assets/posters/{name}.webp" width="{'540' if portrait else '1280'}" height="{'960' if portrait else '720'}" aria-label="{escape(label)}">
        <source data-src="assets/media/{name}.mp4" type="video/mp4">
      </video>{f'<span class="speed-label">{speed}</span>' if speed else ''}
      <button class="video-start" aria-label="Play {escape(label)}"><span aria-hidden="true">▶</span> {escape(label)}</button>
      {('<div class="film-caption" aria-hidden="true"><span class="live-dot"></span><span id="hero-scene">Contact, leverage, retrieve</span><span id="hero-index">01 / 03</span></div>') if autoplay else ''}
    </div>'''


def heading(num, subject, title, copy):
    return f'<div class="section-heading"><p class="eyebrow">{num} / {subject}</p><h2>{title}</h2><p>{copy}</p></div>'


def detail(title, content):
    return f'<details class="research-details"><summary>{title}<span aria-hidden="true">+</span></summary><div class="details-content">{content}</div></details>'


def figure(name, alt, caption):
    return f'<figure><button class="zoom-figure" data-zoom="assets/figures/{name}.webp" aria-label="Enlarge {escape(alt)}"><img src="assets/figures/{name}.webp" alt="{escape(alt)}" loading="lazy"></button><figcaption>{caption}</figcaption></figure>'


html = '''<!doctype html><html lang="en"><head>
<meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>HiFun | Functional Dexterous Manipulation</title>
<meta name="description" content="HiFun learns contact-aware hand skills and when to use them. Hierarchical real-world RL for functional dexterity, evaluated on six tasks with two dexterous hands.">
<meta name="theme-color" content="#f6f4ef"><meta property="og:type" content="website">
<meta property="og:title" content="HiFun: Learning contact skills and when to use them">
<meta property="og:description" content="Contact-aware hand skills. Learned coordination. 295 successful evaluation trials out of 300 across six real-world tasks.">
<meta property="og:image" content="assets/posters/hero.webp">
<link rel="icon" href="favicon.svg" type="image/svg+xml"><link rel="stylesheet" href="assets/fonts/fonts.css"><link rel="stylesheet" href="styles.css"><script src="script.js" defer></script>
</head><body><a class="skip-link" href="#main">Skip to content</a>
<header class="site-header"><nav class="nav container" aria-label="Main navigation"><a class="brand" href="#top" aria-label="HiFun home"><span class="brand-symbol" aria-hidden="true"><i></i><i></i></span>HiFun<span class="brand-dot">.</span></a><button class="menu-toggle" aria-expanded="false" aria-controls="nav-links">Menu <span aria-hidden="true">☰</span></button><div class="nav-links" id="nav-links"><a href="#demos">Demos</a><a href="#insights">Insights</a><a href="#method">Method</a><a href="#results">Results</a><a href="#resources">Resources</a></div></nav><div class="progress-track" aria-hidden="true"><span id="progress"></span></div></header>
<main id="main"><section class="hero" id="top"><div class="container hero-inner"><p class="eyebrow">Real-world robot learning</p><div class="wordmark" aria-hidden="true">Hi<span>Fun</span><b>.</b></div><h1>A Hierarchical Framework for Efficient<br class="desktop-break"> Functional Dexterous Manipulation Learning</h1>
<div class="authors" aria-label="Authors"><span>Linyi Huang<sup>1</sup></span><span>Guowei Huai<sup>1</sup></span><span>Weibin Liu<sup>1</sup></span><span>Shulong Jiang<sup>1</sup></span><span>Ping Tan<sup>2</sup></span><span>Hui Zhang<sup>3</sup></span><a href="https://facultyprofiles.hkust-gz.edu.cn/faculty-personal-page/SONG-Jie/jsongroas">Jie Song<sup>1,2</sup></a></div>
<p class="affiliations"><span><sup>1</sup> HKUST (Guangzhou)</span><span><sup>2</sup> HKUST</span><span><sup>3</sup> ETH Zurich</span></p>
<div class="resource-buttons"><a class="button button-dark" href="assets/documents/paper.pdf">Paper ↗</a><a class="button" href="assets/documents/appendix.pdf">Appendix ↗</a><a class="button" href="#full-video">Full video ↗</a><span class="release-status"><i></i>Code not yet released</span></div>
<p class="hero-thesis">Learning <span class="text-skill">contact skills</span> and <span class="text-coord">when to use them.</span></p>
'''
html += film('hero', 'Watch HiFun', autoplay=True)
html += '''<div class="film-footnote"><span>Real robot executions · edited excerpts</span><span>Recovery includes an additional key-turning example.</span></div>
<div class="headline-metrics" aria-label="Main evaluation summary"><div><strong>295<span>/300</span></strong><p>successful evaluation trials</p></div><div><strong>6</strong><p>functional manipulation tasks</p></div><div><strong>2</strong><p>dexterous hand embodiments</p></div><div><strong>≤60<span> min</span></strong><p>online HIL per task<a href="#training-cost" aria-label="See full training costs">*</a></p></div></div>
<p class="source-note hero-note">98.3% mean success. 50 trials per task within the trained workspace. Online HIL is one training stage; the full pipeline averages approximately 109 min/task. <a href="assets/documents/paper.pdf#page=6">Evaluation details ↗</a></p></div></section>
<section class="section section-white" id="demos"><div class="container">'''
html += heading('01', 'Functional dexterity', 'A useful grasp starts<br>with the right contact.', 'A thin handle sits inside a narrow opening. The fingers must first create access, then form a precision grasp while the arm moves the tool clear of its surroundings.')
html += '<div class="demo-layout"><figure>' + film('thin-handle', 'Watch the contact sequence') + '<figcaption>Thin-Handle Retrieval · Sharpa hand · source timing preserved</figcaption></figure><ol class="contact-sequence">'
for i, (title, text) in enumerate([('Establish contact', 'Place the fingers on the exposed, task-relevant part of the handle.'), ('Create clearance', 'Lever the handle into a position that permits a grasp.'), ('Secure the tool', 'Transition to a precision grasp without losing contact.'), ('Complete the retrieval', 'Coordinate the arm and fingers to clear the opening.')], 1):
    html += f'<li><span>0{i}</span><div><h3>{title}</h3><p>{text}</p></div></li>'
html += '</ol></div><p class="takeaway"><span>Design principle</span>Separate the mechanics of contact from the decision about where and when to use it.</p></div></section><section class="section" id="insights"><div class="container">'
html += heading('02', 'Research insights', 'What makes the hierarchy work?', 'Three views of the evidence: adapting finger contact, learning arm–skill coordination, and using corrections selectively.')
html += '''<article class="insight"><div class="insight-heading"><span class="insight-number text-skill">01</span><div><p class="eyebrow text-skill">Contact-aware hand skills</p><h3>The fingers can recover a lost contact.</h3><p>A collision rotates the key and breaks thumb contact. The residual hand skill adjusts the fingers to restore contact without arm re-alignment.</p></div></div><figure class="wide-evidence">'''
html += film('contact-recovery', 'Watch contact recovery · 1×', speed='1×')
html += '''<figcaption><strong>Contact lost → finger adjustment → contact restored.</strong> Submitted supplementary video, 0:27–0:34. Key turning is an additional skill example, outside the six-task main evaluation.</figcaption></figure><div class="evidence-strip"><div><strong>19<span>/20</span></strong><h4>Unseen tool orientations</h4><p>Fixed-arm Angle-Spreader skill. Toolbox yaw 0–30°; tool pitch/roll 0–20°.</p></div><div><strong>18<span>/20</span></strong><h4>Unseen drill orientations</h4><p>Fixed-arm Bit Removal skill, with drill yaw up to 30°.</p></div><div><strong>18<span>/20</span></strong><h4>External contact disturbances</h4><p>Fixed-arm Angle-Spreader skill under strong wrench perturbations.</p></div></div><p class="source-note">These experiments support local recovery around a demonstrated contact structure. <a href="assets/documents/additional-evidence.pdf">Additional evaluation, rebuttal ↗</a></p></article>
<article class="insight"><div class="insight-heading"><span class="insight-number text-coord">02</span><div><p class="eyebrow text-coord">Skill-conditioned coordination</p><h3>A hand skill still needs the right timing.</h3><p>Giving a baseline access to the same learned skill improves performance. Learning where to align the arm and when to activate that skill closes a further gap.</p></div></div><div class="comparison-layout"><figure class="chart-panel"><figcaption class="chart-title">Mean task success<span>Four Sharpa tasks · matched training budget</span></figcaption><div class="bar-chart" role="img" aria-label="Four-task mean reported success: flat HIL-SERL with the same skill intervention interface 12.5 percent, Skill-HIL 46 percent, HiFun 100 percent.">'''
for label, sub, value, color in [('Flat HIL-SERL', 'same skill intervention interface', '12.5', 'neutral'), ('Skill-HIL', 'learned skill as an action primitive', '46', 'blue'), ('HiFun', 'skill-conditioned coordination', '100', 'green')]:
    html += f'<div class="bar-row"><div class="bar-label">{label}<small>{sub}</small></div><div class="bar-track"><span style="--value:{value}%" class="bar {color}"></span></div><strong>{value}%</strong></div>'
html += '''<div class="bar-axis" aria-hidden="true"><span>0</span><span>50</span><span>100%</span></div></div><p class="source-note">Separate from the six-task 98.3% headline result. <a href="assets/documents/additional-evidence.pdf">Rebuttal comparison ↗</a></p></figure><aside class="evidence-aside"><p class="eyebrow">Additional-data control</p><h4>More data alone<br>leaves a gap.</h4><div class="paired-numbers"><div><strong>35<span>/50</span></strong><p>Skill-HIL<br>with 2× training data</p></div><div><strong class="text-coord">50<span>/50</span></strong><p>HiFun<br>standard budget</p></div></div><p class="small">Angle-Spreader Retrieval. Reported failures involve contact regions, activation timing and subsequent collisions.</p></aside></div></article>
<article class="insight"><div class="insight-heading"><span class="insight-number">03</span><div><p class="eyebrow">Value-guided learning</p><h3>Learn activation timing.<br>Weight useful corrections.</h3><p>Separate value heads train spatial alignment and skill activation. Intervention advantage weighting (IAW) gives more imitation weight to corrections with higher estimated value than the current policy action.</p></div></div>
<div class="analysis-grid"><div class="analysis-block"><p class="chart-kicker">Multi-head critic</p><h4>Activation closer to the target</h4><div class="error-comparison"><div><strong>4.58<small> cm</small></strong><span>without multi-head</span></div><span aria-hidden="true">→</span><div><strong class="text-coord">2.00<small> cm</small></strong><span>HiFun</span></div></div><p>95th-percentile TCP-to-target error at activation, measured on Angle-Spreader Retrieval.</p></div><div class="analysis-block"><p class="chart-kicker">Intervention advantage weighting</p><h4>Selective imitation improves success</h4><div class="ablation-values"><div><strong class="text-coord">100%</strong><span>HiFun</span></div><div><strong>60%</strong><span>Uniform<br>intervention BC</span></div><div><strong>40%</strong><span>No intervention<br>BC loss</span></div></div><p>The same success rates are reported on each of Angle-Spreader Retrieval and Bit Removal.</p></div></div>'''
html += detail('Inspect the component evidence', figure('coordination-analysis', 'Coordination component analysis', 'Original Appendix Fig. 4. IAW estimates usefulness through a critic; it does not directly observe the true quality of a human correction.') + '<p class="source-note"><a href="assets/documents/paper.pdf#page=7">Main paper, Table 2 ↗</a> · <a href="assets/documents/appendix.pdf#page=6">Appendix D.3 ↗</a></p>')
html += '</article></div></section><section class="section section-white" id="method"><div class="container">'
html += heading('03', 'Method', 'Two levels.<br>One physical interaction.', 'A learned hand skill executes precise contact. A coordination policy controls arm motion and hand-skill activation through a compact interface.')
html += '''<div class="method-diagram" role="group" aria-label="HiFun execution architecture"><div class="method-observation"><span class="diagram-label">Observation</span><p>RGB images · arm–hand state · contact feedback</p></div><div class="policy-pair"><div class="policy policy-skill"><span class="policy-id">π<sub>skill</sub></span><h3>How to contact</h3><p>Kinesthetic reference + residual RL</p><div class="policy-output">Contact-aware finger commands</div><small>Weights frozen during coordination learning;<br>execution remains feedback-conditioned.</small></div><div class="policy policy-coord"><span class="policy-id">π<sub>coord</sub></span><h3>Where / when to activate</h3><p>Learned arm–hand coordination</p><div class="policy-output">6D arm motion Δx + activation α</div><small>Arm motion and skill activation are learned;<br>a fixed move–stop–act sequence is not imposed.</small></div></div><div class="execution-output"><span aria-hidden="true">↓</span><div><strong>Coordinated arm–hand execution</strong><p>The activation value blends the hand-skill command with the neutral hand configuration.</p></div></div></div>'''
html += detail('Training stages and complete framework', '<ol class="training-stages"><li><strong>Acquire a contact-aware hand skill.</strong> Start with a kinesthetic reference and refine finger execution with residual RL on the real robot.</li><li><strong>Warm-start coordination.</strong> Generate 100 physical DMP rollouts from an arm-and-activation demonstration, then pretrain the coordination policy.</li><li><strong>Refine with online interaction.</strong> Use skill-level human corrections, separate value heads and intervention advantage weighting.</li></ol>' + figure('method', 'Complete HiFun framework', 'Main paper, Fig. 2. The hand skill is also the human operator’s intervention interface. <a href="assets/documents/paper.pdf#page=3">Read the method ↗</a>'))
html += '</div></section><section class="section" id="results"><div class="container">'
html += heading('04', 'Real-world evaluation', 'Six tasks.<br>Functional outcomes, measured.', 'Each task is evaluated over 50 trials with randomized object poses inside the trained workspace. Success requires completing the functional outcome.')
html += '<div class="task-grid">'
tasks = [
    ('A', 'Precise tool use', 'Sharpa', 'Power-Drill Actuation', 'power-drill', 50, 'Tighten the target screw while maintaining alignment and actuating the trigger.'),
    ('B', 'Constrained space', 'Sharpa', 'Angle-Spreader Retrieval', 'angle-spreader', 50, 'Establish fingertip contact and fully extract the tool from its constrained tray.'),
    ('C', 'Constrained space', 'Sharpa', 'Thin-Handle Retrieval', 'thin-handle', 50, 'Lever an exposed handle into reach, form a precision grasp and fully extract it.'),
    ('D', 'Contact-rich rotation', 'Sharpa', 'Power-Drill Bit Removal', 'bit-removal', 50, 'Maintain multi-finger contact while loosening the chuck, then remove the drill bit.'),
    ('E', 'Precise tool use', 'XHand', 'Pipette Dispensing', 'pipette', 45, 'Align the tip with the vial and dispense liquid without collision or leakage.'),
    ('F', 'Constrained space', 'XHand', 'Thin-Shaft Tool Retrieval', 'thin-shaft', 50, 'Use a fingertip contact sequence to fully retrieve a thin shaft embedded in foam.')]
for code, category, hand, title, name, count, copy in tasks:
    html += f'<article class="task"><div class="task-heading"><div><span class="task-category">{code} / {category} · {hand}</span><h3>{title}</h3></div><span class="success-count">{count}<small>/50</small></span></div>' + film(name, title, portrait=name == 'pipette', speed='5×' if name == 'pipette' else '', loop=False) + f'<p>{copy}</p></article>'
html += '</div><p class="source-note">Clips are illustrative edited excerpts, not the complete 50-trial records. Source timing is preserved; recording multipliers are shown where documented. <a href="assets/documents/paper.pdf#page=6">Main paper, Table 1 ↗</a></p>'
html += detail('Baseline comparison and evaluation protocol', '''<div class="table-scroll" role="region" aria-label="Six-task baseline results" tabindex="0"><table><caption>Six-task mean reported success (%)</caption><thead><tr><th scope="col">Method</th><th scope="col">Mean</th><th scope="col">Training setup</th></tr></thead><tbody><tr><th scope="row">HiFun</th><td><strong>98.3</strong></td><td>Hierarchical RL, 100 DMP rollouts + online HIL</td></tr><tr><th scope="row">HIL-SERL (same skill intervention)</th><td>13.7</td><td>Flat full-DoF RL, matched buffer and online budget</td></tr><tr><th scope="row">HIL-SERL (Glove + Gello)</th><td>4.5</td><td>Flat full-DoF RL with direct teleoperation</td></tr><tr><th scope="row">Behavior Cloning</th><td>23.7</td><td>200 successful human demonstrations per task</td></tr><tr><th scope="row">Diffusion Policy</th><td>41.7</td><td>200 successful human demonstrations per task</td></tr></tbody></table></div><p class="small">The Appendix assigns 0.5 credit to rare baseline trials that reach final contact but time out before completing the task. Unreliable teleoperation settings marked “–” in the main table count as zero in its average. These baseline scores should not be interpreted as counts of fully completed trials. The six-task table is separate from the four-task Skill-HIL comparison above.</p><p class="source-note"><a href="assets/documents/appendix.pdf#page=3">Appendix B.3, evaluation protocol ↗</a></p>''')
html += '<div class="subsection-heading"><p class="eyebrow">Beyond nominal rollouts</p><h3>Recovery and local transfer</h3><p>Deployment on two hands demonstrates portability of the framework. Size transfer tests reuse of a hand skill around the demonstrated contact structure.</p></div><div class="extension-grid">'
html += '<figure>' + film('spreader-disturbance', 'Tray disturbance') + '<figcaption><strong>Changed object placement.</strong> A moved tray requires coordination to adapt the approach.</figcaption></figure>'
html += '<figure>' + film('shaft-disturbance', 'XHand recovery') + '<figcaption><strong>Framework deployment on XHand.</strong> This does not claim unchanged policy transfer between hand embodiments.</figcaption></figure></div>'
html += '<figure class="transfer-feature">' + film('size-transfer', 'Same skill, different sizes', speed='2×') + '<figcaption><strong>7.5 cm → 6.5 cm / 5.5 cm.</strong> The same hand skill transfers to smaller tool variants. This is local size transfer, not open-ended object or task generalization. <a href="assets/documents/additional-evidence.pdf">Source ↗</a></figcaption></figure></div></section>'
html += '<section class="section section-white" id="training-cost"><div class="container">' + heading('05', 'Learning cost & autonomy', 'What does the training budget include?', 'Online HIL fine-tuning averages 46.2 minutes per task. Including hand-skill learning and preparation, the reported full pipeline averages approximately 109 minutes per task.')
html += '<div class="cost-layout"><div class="cost-summary"><strong>~109<span> min/task</span></strong><p>Reported full-pipeline average</p><a href="assets/documents/additional-evidence.pdf">Training-cost clarification ↗</a></div><div class="cost-stages">'
for name, time in [('Kinesthetic reference', '&lt;5 min'), ('Hand-skill residual RL', '~30 min'), ('Reward-classifier data', '8.8 min avg.'), ('Automated DMP rollouts', '18.8 min avg.'), ('Online HIL coordination', '46.2 min avg.')]:
    html += f'<div><span>{name}</span><strong>{time}</strong></div>'
html += '</div></div><p class="source-note">Stage values are approximate or rounded. The ~109-minute total follows the rebuttal’s full-cost accounting; reported times include resets and interventions. <a href="assets/documents/appendix.pdf#page=3">Appendix C.1 ↗</a></p><div class="subsection-heading"><h3>Human guidance decreases during training.</h3><p>Intervention rate complements success: it measures how much human correction is still needed. The original curves below show intervention rate and cycle time across the six tasks.</p></div><div class="training-figure">'
html += figure('training-curves', 'Intervention rate and cycle time across six tasks', 'Original Appendix Fig. 3. Running averages over 20 episodes. The original figure uses orange for HiFun and blue for HIL-SERL. <a href="assets/documents/appendix.pdf#page=5">Source ↗</a>')
html += '</div></div></section><section class="section" id="resources"><div class="container">'
html += heading('06', 'Explore the work', 'From the behavior<br>to the details.', 'Read the method and evaluation, watch the full supplementary video, or explore the additional evidence introduced during review.')
html += '<div class="resource-list">'
for name, filename, desc in [('Paper', 'paper.pdf', 'Method, main results and limitations'), ('Supplemental appendix', 'appendix.pdf', 'Protocols, learning curves and component analysis'), ('Additional evidence', 'additional-evidence.pdf', 'Rebuttal: Skill-HIL, recovery and training-cost clarification')]:
    html += f'<a href="assets/documents/{filename}"><span><strong>{name}</strong><small>{desc}</small></span><span aria-hidden="true">↗</span></a>'
html += '<div class="resource-unavailable"><span><strong>Code</strong><small>Implementation repository not yet publicly released</small></span><span class="availability">Not yet released</span></div></div><figure class="full-video" id="full-video">'
html += film('supplementary', 'Full supplementary video · 3 min', loop=False) + '<figcaption>Submitted supplementary video. Playback multipliers appear in the footage. <a href="assets/media/supplementary.mp4" download>Download web video ↓</a></figcaption></figure>'
html += detail('Abstract', '''<div class="abstract"><p>While multi-fingered dexterous robot hands have the potential to provide human-level dexterity, using them for functional manipulation remains difficult because task success depends on precise contact, coordinated arm-hand motion, and reactive recovery from execution errors. Precise contact depends on complex contact dynamics that are difficult to model accurately in simulation, motivating real-world learning. However, real-world demonstrations in the full arm-hand control space are costly and noisy because each trajectory must coordinate arm motion with high-DoF multi-finger contact. Small execution deviations can further cause slipped contact or premature force application, making recovery from off-nominal contact states important for robust execution.</p><p>To deal with these challenges, we propose HiFun, a hierarchical real-world RL framework for functional dexterous manipulation tasks. Our key insight is to decouple the control complexity into a functional hand skill for precise contact execution and an arm-hand coordination policy for arm control and hand-skill activation. This design enables effective real-time human intervention for reactive recovery learning and efficient data collection with Dynamic Movement Primitive (DMP) augmentation. Across six real-world tasks on two dexterous hands, HiFun achieves 98.3% average success within one hour of online training and remains robust to dynamic disturbances.</p><p class="source-note">Abstract from the supplied manuscript. “Within one hour” refers to online HIL coordination training.</p></div>''')
html += detail('Scope and next directions', '<p>HiFun relies on task-relevant hand skills learned around kinesthetic priors. New contact structures may require additional priors or adaptation. The current evaluation establishes functional execution within trained workspaces and local contact variations, rather than language-conditioned or open-ended task generalization.</p><p>Reusable hand-skill libraries and integration with high-level task-selection models are research directions. They are not evaluated capabilities of the current system.</p><p class="source-note"><a href="assets/documents/paper.pdf#page=8">Main paper, Limitations ↗</a></p>')
html += '''<div class="citation-section"><div class="citation-heading"><h3>Citation</h3><button class="copy-button" id="copy-citation">Copy BibTeX</button></div><pre id="citation"><code>@misc{huang2026hifun,
  title = {HiFun: a Hierarchical Framework for Efficient
           Functional Dexterous Manipulation Learning},
  author = {Huang, Linyi and Huai, Guowei and Liu, Weibin and
            Jiang, Shulong and Tan, Ping and Zhang, Hui and Song, Jie},
  year = {2026},
  note = {Manuscript}
}</code></pre><p class="source-note">Manuscript citation; no acceptance or publication status is implied.</p><span id="copy-status" class="sr-only" role="status"></span></div></div></section></main>
<footer><div class="container footer-inner"><a class="brand" href="#top">HiFun<span class="brand-dot">.</span></a><p>Contact-aware skills. Learned coordination.</p><a href="#top">Back to top ↑</a></div><div class="container footer-credit">Visual direction inspired by <a href="https://siriyep.github.io/last-hd-project-page/">LaST-HD</a>. Robot footage and research materials belong to the HiFun project.</div></footer>
<dialog id="figure-dialog" aria-labelledby="figure-dialog-title"><div class="dialog-toolbar"><h2 id="figure-dialog-title">Research figure</h2><button id="close-figure" aria-label="Close enlarged figure">Close ×</button></div><img id="enlarged-figure" alt=""></dialog>
<noscript><style>.video-start{display:none}.menu-toggle{display:none}.nav-links{display:flex!important}</style><p class="noscript-note">JavaScript is disabled. <a href="assets/media/supplementary.mp4">Watch the supplementary video directly.</a> Research text, figures and documents remain available.</p></noscript>
</body></html>'''

html = html.replace('<h1>A Hierarchical', '<h1><span class="sr-only">HiFun: </span>A Hierarchical')
html = '\n'.join(line.rstrip() for line in html.splitlines()) + '\n'
(ROOT / 'index.html').write_text(html, encoding='utf-8')
print('Built index.html')
